builds:
  - main: ./cmd/blobproxy
    ldflags:
      - -s -w -X github.com/logsquaredn/blobproxy.Semver={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - image_templates:
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-amd64
    dockerfile: goreleaser.dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
    skip_push: true
  - image_templates:
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-arm64
    dockerfile: goreleaser.dockerfile
    use: buildx
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64
    skip_push: true
docker_manifests:
  - name_template: ghcr.io/logsquaredn/blobproxy:{{ .Version }}
    image_templates:
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-amd64
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-arm64
  - name_template: ghcr.io/logsquaredn/blobproxy:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-amd64
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-arm64
  - name_template: ghcr.io/logsquaredn/blobproxy:{{ .Major }}
    image_templates:
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-amd64
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-arm64
  - name_template: ghcr.io/logsquaredn/blobproxy:latest
    image_templates:
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-amd64
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}-arm64
