builds:
  - main: ./cmd/blobproxy
    ldflags:
      - -s -w -X github.com/logsquaredn/blobproxy.Semver={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
dockers:
  - image_templates:
      - ghcr.io/logsquaredn/blobproxy:{{ .Version }}
      - ghcr.io/logsquaredn/blobproxy:{{ .Major }}.{{ .Minor }}
      - ghcr.io/logsquaredn/blobproxy:{{ .Major }}
      - ghcr.io/logsquaredn/blobproxy:latest
    dockerfile: goreleaser.dockerfile
