name: CI
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install_args: dagger
      - run: dagger check
      - name: Run dagger ship
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          dagger call ship
          --github-token=env://GITHUB_TOKEN
          --github-repo=${{ github.repository }}
